# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - tools/pylint-extensions/pylint_guidelines_checker

pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - tools/pylint-extensions/pylint_guidelines_checker

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-tool-python.yml
  parameters:
    PythonVersion: '3.10.2'
    PackagePath: 'tools/pylint-extensions/pylint_guidelines_checker'
    FeedName: 'public/azure-sdk-for-python'
    ArtifactName: 'azsdkpylintplugin'
    PackageName: 'Azure SDK Pylint Plugin'
    TestSteps:
    - script: |
        pip install -r dev_requirements.txt
        pip install -e .
      displayName: 'Install Test Requirements'
      workingDirectory: $(Build.SourcesDirectory)/tools/pylint-extensions/pylint_guidelines_checker

    - script: |
        pytest .
      displayName: 'Test Python Linter'
      workingDirectory: $(Build.SourcesDirectory)/tools/pylint-extensions/pylint_guidelines_checker
      continueOnError: true
